### PR TITLE
add react 17 to peer deps

### LINKED ISSUE #8: Update peer dependency for React 17
```
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-delta@1.1.0
```

### PR DESCRIPTION
**Pull request by SpadarShut**
react-delta fails to install on projects with react 17. This should fix https://github.com/malerba118/react-delta/issues/8.

### CODE REVIEW

**Comment by malerba118** [comment]
Thanks!

**Comment by malerba118** [comment]
published [v1.1.1](https://www.npmjs.com/package/react-delta/v/1.1.1) with that change

**Comment by SpadarShut** [comment]
Thanks! 
Tried to install and found that react-dom also requires an update. Could you please fix it?

**Comment by malerba118** [comment]
How about this? https://www.npmjs.com/package/react-delta/v/1.1.2

**Comment by SpadarShut** [comment]
Yep, installed. Thanks a lot!

**Pull request merged**
